#!/bin/bash
work_time=3
pause_time=1
loop_amount=2
big_break=2

function pause_p {
    read -t 0.1 -n 1 key
    if [[ $key == "p" ]]; then
        print_stats $1 $2
        echo "Timer paused. Press any key to resume."
        read -n 1
        print_stats $1 $2
        
    fi
}

function print_stats {
    # i(cycle), ..._time, "...", min
    clear
    echo "$3"
    echo "Cycle: ${1} [$loop_amount]"
    echo "Time: ${4} [$2]"
     
}

function time_module {
    sec=0
    min=0

    print_stats $1 $2 $3 $min  

    while (($sec<$2*60))
    do
        pause_p $1 $min

        sleep 0.1
        ((sec++))
        # echo "$sec"
        
        # check if a minute went by than update stats
        if [[ $sec == $(($min*60 + 60)) ]]; then
            ((min++))
            print_stats $1 $2 $3 $min  
        fi
    done
}

# clear screen
clear
tput civis

while true
do
    
    for ((i=1; i<=$loop_amount; i++))
    do
        
        time_module $i $work_time "Work"
        if [[ i!=$loop_amount ]]; then
            time_module $i $pause_time "Pause"
        fi
    done

    echo "----------------_"
    sleep 3
    
    j=1
    time_module $j $break_time "Break"

done
