#!/bin/bash

# nmcli r wifi on
# pipe the availabe networks into dmenu
connections=$(nmcli d wifi list | tail -n +2 | awk '{print $1}')

selected=$(echo "$connections" | dmenu)

# connections=$(nmcli d wifi list)
#
# selected=$(printf '%s\n' "${connections[@]}" | dmenu -i)
